### PR TITLE
Adding pick -> pickBy change

### PR DESCRIPTION
**Pull request by KamranAsif**
Missing pick -> pickBy change.
Also added some tests for omitBy

### CODE REVIEW

**Comment by jfmengels** [comment]
Awesome! Thanks a lot! :smile: 

(Tests fail, but that's actually something on my side it seems)

**Comment by KamranAsif** [comment]
Thanks for merging it! Will you be republishing on npm? Need to update my package.json to include this changeset.

**Comment by jfmengels** [comment]
Just published v1.0.1 ;)

**Comment by KamranAsif** [comment]
Awesome, thanks!

**Pull request merged**
